### ISSUE TITLE
Resampling results in blurred images

### ISSUE THREAD

**Issue by reyemtm** [geomatico/maplibre-cog-protocol#14] opened 2024-09-23 15:15 UTC
same COG, OpenLayers (right) vs this library with maplibre(left)  - the jagged lines on the left image (maplibre) are signs of resampling artifacts, which disappear once you zoom in to the native resolution. OpenLayers is using the same underlying library so it's likely in the implementation or options sent to geotiff.js, unless OL is only using the native resolution and then downscaling outside of geotiff.js.

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/2e71f8a7-379e-440b-bcbf-a3c75d42b76f">

**Comment by reyemtm** [comment] 2024-10-08 14:58
I'm running my own fork and have a static min and max zoom so don't think that's it - though maybe it's something similar in the rest of the code.

**Comment by oscarfonts** [comment] 2024-11-07 09:59
The idea is to generate a COG using `TILING_SCHEME=GoogleMapsCompatible`, see (COG Generation Tips)[https://github.com/geomatico/maplibre-cog-protocol?tab=readme-ov-file#cog-generation-tips] on README.
So the images don't need to be resampled or reprojected client side, for performance and simplicity reasons.

My initiak  guess was that your COG's internal resolutions don't match the ones of "google maps" tiling scheme, the images need to be interpolated, and "nearest neighbor" is causing the pixelation:
https://github.com/geomatico/maplibre-cog-protocol/blob/main/src/read/CogReader.ts#L110

But still, the pixelation is too harsh and even the contrast doesn't seem to be the same in both images (see shadows), which is strange. Are you sure to be using the same COG with the required tiling schema, and good quality overviews?

In the code, we use Math.round precisely to remove rounding errors from zoom computation, but expect them to be very close to a whole number, because the overview resolutions should match the ones the viewer needs at integer zoom levels. So, for instance, we want a minzoom of 3.99 to be rounded to 4, not floored to 3.

Side note: MinZoom and MaxZoom can always be narrowed in the style (at layer level) if for whatever reason the computed ones are beyond the desired visualization range.

Closing the issue as cannot reproduce. Our imagery (renders nicely)[https://labs.geomatico.es/maplibre-cog-protocol/photo.html#18/41.593299/1.837597].

If your image quality issues persists and cannot find the cause, please provide a minimal reproductible example (image sample and code) so we can investigate further.

**Closed by oscarfonts** 2024-11-07 09:59 UTC
